[general]
repository = "https://thunderstore.io"

[package]
name = "GaleModManager"
namespace = "Kesomannen"
description = "A modern and lightweight mod manager for many games on Thunderstore."
websiteUrl = "https://github.com/Kesomannen/gale"

[build]
icon = "images/icons/app-icon@0,25x.png"

[[build.copy]]
source = "CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "LICENSE.md"
target = "LICENSE.md"

[[build.copy]]
pattern = "src-tauri/target/release/bundle/msi/*.msi"
target = ""

[publish]
categories = ["tools"]
communities = [
    "20-minutes-till-dawn",
    "9-kings",
    "against",
    "among-us",
    "aneurism-iv",
    "aska",
    "atlyss",
    "across-the-obelisk",
    "against-the-storm",
    "ale-and-tale-tavern",
    "aloft",
    "ancient-dungeon-vr",
    "another-crabs-treasure",
    "arcus-chroma",
    "atomicrops",
    "atrio-the-dark-wild",
    "bad-north",
    "bonelab",
    "boneworks",
    "back-to-the-dawn",
    "backpack-hero",
    "balatro",
    "below-the-stone",
    "betrayal-beach",
    "bomb-rush-cyberfunk",
    "bopl-battle",
    "castle-story",
    "cats-are-liquid",
    "chrono-ark",
    "cities-skylines-ii",
    "clover-pit",
    "content-warning",
    "core-keeper",
    "cult-of-the-lamb",
    "depo",
    "dredge",
    "dusk",
    "deep-rock-galactic-survivor",
    "disco-elysium",
    "distance",
    "dyson-sphere-program",
    "easy-delivery-co",
    "ena-dream-bbq",
    "enter-the-gungeon",
    "erenshor",
    "five-nights-at-freddys-into-the-pit",
    "for-the-king",
    "gtfo",
    "gang-beasts",
    "garfield-kart-furious-racing",
    "gatekeeper",
    "gladio-mori",
    "gloomwood",
    "goodbye-volcano-high",
    "gorebox",
    "green-hell-vr",
    "guilty-as-sock",
    "h3vr",
    "hades-ii",
    "hard-bullet",
    "hard-time-3",
    "hollow-knight-silksong",
    "hotds",
    "house-of-legacy",
    "human-fall-flat",
    "i-am-your-beast",
    "inscryption",
    "jump-space",
    "labyrinthine",
    "last-train-outta-wormtown",
    "lens-island",
    "lethal-company",
    "lethal-league-blaze",
    "logic-world",
    "lost-skies",
    "lost-skies-ic",
    "lycans",
    "mage-arena",
    "magicite",
    "magicraft",
    "malteses-fluffy-onsen",
    "mechanica",
    "meeple-station",
    "megabonk",
    "miside",
    "monster-train-2",
    "muck",
    "my-dream-setup",
    "mycopunk",
    "nearly-dead",
    "nasb",
    "nine-sols",
    "odd-remedy",
    "old-market-simulator",
    "ostranauts",
    "outward",
    "paper-animal-adventure",
    "patapon-1-2-replay",
    "peak",
    "pigface",
    "painting-vr",
    "palworld",
    "panicore",
    "paquerette-down-the-bunburrows",
    "patch-quest",
    "peaks-of-yore",
    "peglin",
    "plasma",
    "potion-craft",
    "pulsar-lost-colony",
    "repo",
    "rounds",
    "rumble",
    "ravenfield",
    "receiver-2",
    "return-of-the-obra-dinn",
    "resonite",
    "risk-of-rain-returns",
    "riskofrain2",
    "rogue-genesia",
    "rogue-tower",
    "straftat",
    "sulfur",
    "sailwind",
    "schedule-i",
    "screw-drivers",
    "shadows-over-loathing",
    "shadows-of-doubt",
    "shapez-2",
    "skul-the-hero-slayer",
    "slipstream-rogue-space",
    "songs-of-conquest",
    "sons-of-the-forest",
    "stacklands",
    "starsand",
    "subnautica",
    "subnautica-below-zero",
    "subterranauts",
    "subterror",
    "sun-haven",
    "sunkenland",
    "supermarket-together",
    "totally-accurate-battle-simulator",
    "tcg-card-shop-simulator",
    "talespire",
    "tank-team",
    "techtonica",
    "the-ouroboros-king",
    "the-planet-crafter",
    "thronefall",
    "timberborn",
    "northstar",
    "touhou-lost-branch-of-legend",
    "trombone-champ",
    "ultrakill",
    "ultimate-chicken-horse",
    "v-rising",
    "vtol-vr",
    "valheim",
    "vellum",
    "vertigo-2",
    "voices-of-the-void",
    "void-crew",
    "webfishing",
    "we-love-katamari-reroll-royal-reverie",
    "west-of-loathing",
    "white-knuckle",
    "wildfrost",
    "wizard-with-a-gun",
    "wizard-of-legend",
    "word-play",
    "wrestling-empire",
    "zort",
]
