[general]
repository = "https://thunderstore.io"

[package]
name = "GaleModManager"
namespace = "Kesomannen"
description = "A modern and lightweight mod manager for many games on Thunderstore."
websiteUrl = "https://github.com/Kesomannen/gale"

[build]
icon = "images/icons/app-icon@0,25x.png"

[[build.copy]]
source = "CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "LICENSE.md"
target = "LICENSE.md"

[[build.copy]]
pattern = "src-tauri/target/release/bundle/msi/*.msi"
target = ""

[publish]
communities = [
    "boneworks",
    "content-warning",
    "gtfo",
    "h3vr",
    "lethal-company",
    "riskofrain2",
    "northstar",
    "valheim",
    "webfishing",
    "20-minutes-till-dawn",
    "against",
    "across-the-obelisk",
    "against-the-storm",
    "ale-and-tale-tavern",
    "aloft",
    "among-us",
    "ancient-dungeon-vr",
    "another-crabs-treasure",
    "arcus-chroma",
    "atlyss",
    "atomicrops",
    "atrio-the-dark-wild",
    "bonelab",
    "back-to-the-dawn",
    "backpack-hero",
    "below-the-stone",
    "betrayal-beach",
    "bomb-rush-cyberfunk",
    "bopl-battle",
    "castle-story",
    "cats-are-liquid",
    "chrono-ark",
    "cities-skylines-ii",
    "core-keeper",
    "cult-of-the-lamb",
    "dredge",
    "deep-rock-galactic-survivor",
    "dyson-sphere-program",
    "enter-the-gungeon",
    "erenshor",
    "for-the-king",
    "garfield-kart-furious-racing",
    "gladio-mori",
    "gloomwood",
    "goodbye-volcano-high",
    "green-hell-vr",
    "hard-bullet",
    "hotds",
    "inscryption",
    "last-train-outta-wormtown",
    "lethal-league-blaze",
    "lycans",
    "magicraft",
    "mechanica",
    "meeple-station",
    "muck",
    "nearly-dead",
    "nasb",
    "nine-sols",
    "outward",
    "palworld",
    "panicore",
    "patch-quest",
    "peglin",
    "plasma",
    "potion-craft",
    "risk-of-rain-returns",
    "rounds",
    "rumble",
    "ravenfield",
    "receiver-2",
    "rogue-genesia",
    "rogue-tower",
    "sailwind",
    "screw-drivers",
    "shadows-over-loathing",
    "shadows-of-doubt",
    "skul-the-hero-slayer",
    "slipstream-rogue-space",
    "sons-of-the-forest",
    "stacklands",
    "starsand",
    "straftat",
    "subnautica",
    "subnautica-below-zero",
    "sun-haven",
    "sunkenland",
    "supermarket-together",
    "totally-accurate-battle-simulator",
    "tcg-card-shop-simulator",
    "talespire",
    "techtonica",
    "the-ouroboros-king",
    "the-planet-crafter",
    "thronefall",
    "timberborn",
    "touhou-lost-branch-of-legend",
    "trombone-champ",
    "ultrakill",
    "ultimate-chicken-horse",
    "v-rising",
    "vtol-vr",
    "vertigo-2",
    "voices-of-the-void",
    "void-crew",
    "we-love-katamari-reroll-royal-reverie",
    "west-of-loathing",
    "wildfrost",
    "wizard-with-a-gun",
    "wizard-of-legend",
    "wrestling-empire",
]
categories = ["tools"]
