[general]
repository = "https://thunderstore.io"

[package]
name = "GaleModManager"
namespace = "Kesomannen"
description = "A modern and lightweight mod manager for many games on Thunderstore."
websiteUrl = "https://github.com/Kesomannen/gale"

[build]
icon = "app-icon@0,25x.png"

[[build.copy]]
source = "CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "LICENSE.md"
target = "LICENSE.md"

[[build.copy]]
pattern = "src-tauri/target/release/bundle/msi/*.msi"
target = ""

[publish]
communities = ["lethal-company"]
categories = ["tools"]
